version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./dockerfile/dev/django/dockerfile
    volumes:
      - ./core:/usr/src/app
    environment:
      - DEBUG=True
    restart: always
    depends_on:
      - db

  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - '5000:80'

      - '25:25'

      - '143:143'
    volumes:

      - smtp4dev-data:/smtp4dev

volumes:
  smtp4dev-data: