# Generated by Django 4.2.21 on 2025-07-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Default_profile.svg', upload_to='profile/'),
        ),
    ]
