# Generated by Django 4.2.21 on 2025-07-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/Default_profile.svg', upload_to='profile/'),
        ),
    ]
