# Generated by Django 4.2.21 on 2025-05-29 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
