# Generated by Django 4.2.21 on 2025-08-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_wishlistproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='avg_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
