# Generated by Django 4.2.21 on 2025-08-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordermodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (4, 'موفقیت آمیز'), (5, 'لغو شده')], default=1),
        ),
    ]
