# Generated by Django 4.2.21 on 2025-08-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date']},
        ),
    ]
